name: make distribution package
description: Create a release package with release and debug binaries

inputs:
  debug-package-name:
    required: true
    type: string
    description: The name of the debug build job
  release-package-name:
    required: true
    type: string
    description: The name of the release build job
runs:
  using: composite
  steps:

    - name: fetch debug package
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.debug-package-name }}
        path: bundle

    - name: fetch release package
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.release-package-name }}
        path: bundle

 
    - name: bundle release and debug build
      id: bundle-zip
      run: |
        python3 SilKit/ci/package.py bundle/*.zip
        PACKAGE=$(ls -1 SilKit-*.zip | sed 's/.zip$//'g)
        echo $PACKAGE
        echo "package-name=$PACKAGE" >> $GITHUB_OUTPUT
      shell: bash

    - name: Upload final SIL Kit package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.bundle-zip.outputs.package-name }}
        path: ${{ steps.bundle-zip.outputs.package-name }}.zip
        if-no-files-found: 'error'
