name: Windows build

on:
  push:
    branches: [ "main" ]

jobs:
  build-win-x64:
    if: ${{ false }} # disable for now
    runs-on: windows-latest
    environment: public-github-runners
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: ./.github/actions/build-cmake-preset
      with:
        preset-name: vs141-x64-release

