on:
  push:
    branches:
      - 'main'
jobs:
  sync_repo:
    name: Sync branch to remote Git project
    runs-on: Linux
    environment: SyncRemoteRepoEnv
    
    steps:
      - run: git tag -d $(git tag -l)
        shell: bash

      - uses: actions/checkout@v1

      - uses: vikabgm/repo-sync-action@main
        with:
          app-key:          ${{ secrets.VECTOR_APP_KEY }}
          app-id:           ${{ secrets.VECTOR_APP_ID }}
          remote-repo-url:  ${{ secrets.REMOTE_REPO_URL }}
          remote-branch:    ${{ secrets.REMOTE_BRANCH }}
          local-branch:     origin/main
