name: Generate Test Reports

on:
  workflow_call:
    inputs:
      report-name:
        required: true
        type: string
      report-artifact:
        required: true
        type: string

jobs:
  make-report:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        name: ${{ inputs.report-name }}
        artifact: ${{ inputs.report-artifact }}
        path: '**/*gtestresults.xml'
        reporter: java-junit
        fail-on-error: false
